### ISSUE TITLE
can not mute ad after unmute in linear

### ISSUE THREAD

**Issue by zba** [kahwee/vpaid-ad#77]
After unmute, using `setAdVolume = 1;`,  `previousAttributes['volume']` remains 0, so 

`if (this.previousAttributes.volume === volume) {` 
https://github.com/kahwee/vpaid-ad/blob/master/src/linear.js#L388

became always true, I think the bug somewhere in the set() method 

https://github.com/kahwee/vpaid-ad/blob/master/src/linear.js#L48

probably  you have to use "current" as "previous"  (exchange two strings in set()) or change condition, to make it check current volume attribute:

`if (this.getAdVolume() === volume) {`

**Comment by kylevv** [comment]
Should be addressed by #109
